services:
  db_service:
    image: sgsk5137/bbapp:db
    container_name: mysqldb
    restart: on-failure
    networks:
      - bbapp-network
    volumes:
      - bbapp-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  app_service:
    image: sgsk5137/bbapp:app
    container_name: bbapp
    restart: on-failure
    networks:
      - bbapp-network
    ports:
      - "1234:80"
    depends_on:
      - db_service

networks:
  bbapp-network:
    driver: bridge
volumes:
  bbapp-db-data:
